---
resolver: lts-21.25

flags:
  autotool-capabilities:
    alloy-use-sat4j: false

packages:
  - autotool-capabilities
  - autotool-capabilities-io-instances

extra-deps:
  - git: https://github.com/fmidue/output-blocks
    commit: e97c5f06a17c5b99f0bed2a733bfbf974304adf3
    subdirs:
      - output-blocks
  - call-alloy-0.6.0.2
  - diagrams-graphviz-1.4.1.1@sha256:e71afa8f89904c2a6a2cb490dba7108c6425779c2174b90bd90dbaf507a9d3dc,1388
  - latex-svg-image-0.2

allow-newer: true
