---
resolver: lts-21.25

flags:
  autotool-capabilities:
    alloy-use-sat4j: false

packages:
  - autotool-capabilities
  - autotool-capabilities-io-instances

extra-deps:
  - git: https://github.com/fmidue/output-blocks
    commit: 17cf98f45928f4a1e4a3e301a2911fddad6e4357
    subdirs:
      - output-blocks
  - call-alloy-0.6.0.2
  - diagrams-graphviz-1.4.1.1@sha256:e71afa8f89904c2a6a2cb490dba7108c6425779c2174b90bd90dbaf507a9d3dc,1388
  - latex-svg-image-0.2

allow-newer: true
