---
name: autotool-capabilities
version: 0.1.0.0

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/fmidue/autotool-capabilities/autotool-capabilities#readme>

dependencies:
  - base >= 4.7 && < 5
  - bytestring
  - call-alloy
  - diagrams-lib
  - diagrams-svg
  - fgl
  - graphviz
  - MonadRandom
  - latex-svg-image
  - output-blocks
  - SHA
  - SVGFonts
  - transformers
  - utf8-string

when:
  condition: flag(alloy-use-sat4j)
  cpp-options: -DALLOY_USE_SAT4J

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Capabilities.Alloy
    - Capabilities.Cache
    - Capabilities.Diagrams
    - Capabilities.Graphviz
    - Capabilities.LatexSvg
    - Capabilities.PlantUml
    - Capabilities.WriteFile

tests:
  autotool-capabilities-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - autotool-capabilities

flags:
  alloy-use-sat4j:
    description: When calling alloy use the SAT4J SAT solver
    manual: true
    default: false
