---
name: autotool-capabilities-io-instances
version: 0.1.0.0

extra-source-files:
  - README.md

description: Please see the README on GitHub at <https://github.com/fmidue/autotool-capabilities/autotool-capabilities-io-instances#readme>

dependencies:
  - autotool-capabilities
  - base >= 4.7 && < 5
  - call-alloy >= 0.6.0.2 && < 0.7
  - call-plantuml
  - containers
  - bytestring
  - diagrams-graphviz
  - diagrams-lib
  - diagrams-svg
  - directory
  - graphviz
  - hxt
  - latex-svg-image
  - string-interpolate
  - SVGFonts
  - svg-builder
  - text
  - xml-conduit

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
    - Capabilities.Alloy.IO
    - Capabilities.Cache.IO
    - Capabilities.Diagrams.IO
    - Capabilities.Graphviz.IO
    - Capabilities.LatexSvg.IO
    - Capabilities.PlantUml.IO
    - Capabilities.WriteFile.IO

tests:
  autotool-capabilitiesio-instances-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - autotool-capabilities-io-instances
